### ISSUE TITLE
Format date in «Last Update»

### ISSUE THREAD

**Issue by cosenal** [marcopaz/is-service-up#8]
`Last update: 291631 seconds ago` --> `Last update: 3 days, ...`

**Comment by marcopaz** [comment]
It was like that before, I decided to remove it because: 1) the update should always be quite frequent so it's unlikely the time will be more than 1 minute (by default the update is every 30 seconds), 2) it makes the code more complex since we now update the timer with javascript.
One possible way to do this is to use some JS library for the visualization and use a data attribute to store the time in seconds, but it'll add a dependency for very little or no gain.

**Comment by cosenal** [comment]
yeah, I was thinking of using moment.js for that, but I buy your point 1), updates must be very frequent indeed or it makes no sense
